# Starship Configuration File

format = "$directory$git_branch$agus$character"
right_format = """$cmd_duration"""
add_newline = false

# Enable All Languages (set to true)
[c]
disabled = false
[cmake]
disabled = false
[haskell]
disabled = false
[python]
disabled = false
[ruby]
disabled = false
[rust]
disabled = false
[perl]
disabled = false
[package]
disabled = false
[lua]
disabled = false
[nodejs]
disabled = false
[java]
disabled = false
[golang]
disabled = false

# Prompt symbols
[character]
success_symbol = "[](#a6e3a1 bold)"
error_symbol = "[](#f38ba8)"
vicmd_symbol = "[](#f9e2af)"

[directory]
format = "[]($style)[ ](bg:#f9e2af fg:#81A1C1)[$path](bg:#1f2328 fg:#BBC3DF bold)[]($style)"
style = "bg:#384148 fg:#384148"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[]($style)[[  ](bg:#1f2328 fg:#A2DD9D bold)$branch](bg:#1f2328 fg:#86AAEC)[ ]($style)"
style = "bg:#384148 fg:##384148"

[git_status]
format = "[]($style)[$ahead](bg:#1f2328 fg:#b4befe)[ ]($style)"
style = "bg:#384148 fg:#384148"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
format = "[]($style)[[神](bg:#1f2328 fg:#eba0ac bold)$duration](bg:#1f2328 fg:#BBC3DF)[ ]($style)"
disabled = false
style = "bg:#384148 fg:#1f2328"

# Agus Feature Configuration
[agus]
format = "[$symbol Agus](fg:#ffcc00)"
symbol = "⚡"
style = "bold fg:#f38ba8"
disabled = false

# Enabling other components like time, status, etc.
[status]
disabled = false
format = "[$status]($style)"
style = "fg:#81A1C1 bg:#1f2328"

[time]
disabled = false
format = "[$time]($style)"
style = "fg:#E1E1E1 bg:#1f2328"

